### PR TITLE
fix: Replace @ts-ignore with proper BarcodeDetector types

### LINKED ISSUE #492: Type Safety: Remove `@ts-ignore` from BarcodeDetector initialization
## Description
The `barcode-scanner` component currently uses a `@ts-ignore` directive to suppress TypeScript errors when instantiating `new BarcodeDetector()`.

This is unsafe because it bypasses type checking entirely and does not properly define the missing API in the project's global type scope.

---

## Steps to Reproduce
1. Open `web-components/src/components/barcode-scanner/barcode-scanner.ts`
2. Navigate to the BarcodeDetector initialization (around line 284)
3. Observe the use of `@ts-ignore` suppressing TypeScript checks

---

## Current Behavior
- TypeScript errors are suppressed using `@ts-ignore`
- No proper type definition exists for `BarcodeDetector`
- Potential type issues are silently ignored

---

## Expected Behavior
- The `BarcodeDetector` global API should be properly typed
- No usage of `@ts-ignore`
- Safe runtime handling when the API is unavailable

---

## Proposed Fix
- Declare the `BarcodeDetector` interface in the global scope (e.g., `window` declaration)
- Remove the `@ts-ignore` directive
- Add a runtime check before instantiation:

```ts
if (typeof BarcodeDetector !== "undefined") {
  const detector = new BarcodeDetector();
}
``` id="code7721"

- Provide a fallback mechanism for unsupported browsers

---

## Impact
- Improves type safety and maintainability
- Prevents silent type-checking bypass
- Ensures better compatibility with unsupported environments

### PR DESCRIPTION
**Pull request by SaitejaKommi**
### What
This PR improves type safety in the `barcode-scanner` component by removing the use of `@ts-ignore` and properly defining the `BarcodeDetector` API.

---

### Problem
The code previously used `@ts-ignore` to suppress TypeScript errors when instantiating `new BarcodeDetector()`.

This is unsafe because:
- It bypasses type checking entirely
- It hides potential issues
- The global API was not formally declared

---

### Changes
- Declared the `BarcodeDetector` type in the global scope
- Removed the `@ts-ignore` directive
- Added a runtime guard before instantiation:
  
```ts
if (typeof BarcodeDetector !== "undefined") {
  const detector = new BarcodeDetector();
}
``` 
---

### Why this is better
- Ensures proper TypeScript type safety
- Eliminates unsafe suppression of compiler errors
- Provides safe fallback behavior for unsupported browsers
- Improves maintainability and code clarity

---

### Testing Done

✅ All tests passing (`vitest` – 148 tests)  
✅ Verified no TypeScript errors using `npx tsc --noEmit`  

### Related issue(s)
- Fixes: #492 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved detection of whether barcode scanning is supported by the browser/device.
  * More reliable fallback when the scanner API is unavailable or initialization fails.
  * Preserved prior behavior: graceful error handling and user-facing warnings remain, ensuring consistent app behavior across environments.

### CODE REVIEW

**Comment by VaiTon** [comment]
@coderabbitai review

File: web-components/src/components/barcode-scanner/barcode-scanner.ts [hunk 1]
```diff
@@ -280,8 +285,9 @@ export class BarcodeScanner extends ConsoleLogMixin(LitElement) {
    */
   private setupBarcodeDetector() {
     try {
-      // Remove the type assertion for BarcodeDetector to avoid TypeScript error
-      // @ts-ignore
+      if (typeof BarcodeDetector === "undefined") {
```
Comment (VaiTon) [inline web-components/src/components/barcode-scanner/barcode-scanner.ts]: Use `if (!("BarcodeDetector" in globalThis)) `

**Review by VaiTon — CHANGES_REQUESTED** [review]

File: web-components/src/components/barcode-scanner/barcode-scanner.ts (hunk 1 above)
Comment (SaitejaKommi) [reply web-components/src/components/barcode-scanner/barcode-scanner.ts]: Thanks for the review. Updated as requested: I replaced the check with if (!("BarcodeDetector" in globalThis)) barcode-scanner.ts and pushed the change. I also ran the test suite locally (148 passing).

**Review by VaiTon — APPROVED** [review]

**Comment by VaiTon** [comment]
Thank you!
